### 200
GET http://localhost:9999/api/timeseries?startTs=2025-02-25 10:55:00&endTs=2025-02-25 10:56:00

### 400
GET http://localhost:9999/api/timeseries?startTs=xxxxx&endTs=yyyyy

### 404
GET http://localhost:9999
