services:
  iot-influxdb:
    image: influxdb:1.8
    container_name: iot-test-influxdb
    restart: unless-stopped
    environment:
      - "INFLUXDB_REPORTING_DISABLED=true"
    volumes:
      - iot-influxdb-data:/var/lib/influxdb
      - iot-influxdb-config:/etc/influxdb
    ports:
      - 8086:8086

volumes:
  iot-influxdb-data:
  iot-influxdb-config:
