services:
  openvpn-client:
    image: openvpn-client:latest
    container_name: openvpn-client
    restart: unless-stopped
    network_mode: host
    cap_add:
      - NET_ADMIN
    volumes:
      - ./profile.ovpn:/profile.ovpn
    command: sh -c "/initvpn.sh"
